import { Octokit } from '@octokit/rest';
import { readdir, readFile } from 'fs/promises';
import { statSync } from 'fs';
import path from 'path';
import { config } from '../utils/config.js';
import { logger } from '../utils/logger.js';

const octokit = new Octokit({ auth: config.github.token });
const { owner, repo } = config.github;

async function getAllFiles(dir, baseDir = dir) {
  const entries = await readdir(dir, { withFileTypes: true });
  const files = [];
  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      if (['node_modules', '.git'].includes(entry.name)) continue;
      files.push(...await getAllFiles(fullPath, baseDir));
    } else {
      files.push({ fullPath, relativePath: path.relative(baseDir, fullPath) });
    }
  }
  return files;
}

async function getOrCreateRef(branchName) {
  // Get default branch SHA
  const { data: repoData } = await octokit.repos.get({ owner, repo });
  const defaultBranch = repoData.default_branch;
  const { data: refData } = await octokit.git.getRef({
    owner, repo, ref: `heads/${defaultBranch}`,
  });
  const baseSha = refData.object.sha;

  // Create branch
  try {
    await octokit.git.createRef({
      owner, repo, ref: `refs/heads/${branchName}`, sha: baseSha,
    });
    logger.info(`Created branch: ${branchName}`);
  } catch (err) {
    if (err.status === 422) {
      logger.info(`Branch ${branchName} already exists`);
    } else throw err;
  }

  return baseSha;
}

export async function pushToGitHub(story, appDir) {
  const { key, summary } = story;
  const slug = summary.replace(/[^a-z0-9]/gi, '-').toLowerCase().slice(0, 30);
  const branchName = `feature/${key}-${slug}`;

  logger.info(`[${key}] Stage 4: Pushing to GitHub branch ${branchName}`);

  const baseSha = await getOrCreateRef(branchName);

  // Get current tree SHA
  const { data: commitData } = await octokit.git.getCommit({ owner, repo, commit_sha: baseSha });
  const baseTreeSha = commitData.tree.sha;

  // Build tree blobs from app files + test-results.txt
  const files = await getAllFiles(appDir);
  const resultsPath = path.join(path.dirname(appDir), 'test-results.txt');
  try {
    files.push({ fullPath: resultsPath, relativePath: 'test-results.txt' });
  } catch {}

  const treeItems = await Promise.all(files.map(async ({ fullPath, relativePath }) => {
    const content = await readFile(fullPath);
    const { data: blob } = await octokit.git.createBlob({
      owner, repo,
      content: content.toString('base64'),
      encoding: 'base64',
    });
    return { path: relativePath, mode: '100644', type: 'blob', sha: blob.sha };
  }));

  // Create tree
  const { data: newTree } = await octokit.git.createTree({
    owner, repo, base_tree: baseTreeSha, tree: treeItems,
  });

  // Create commit
  const { data: newCommit } = await octokit.git.createCommit({
    owner, repo,
    message: `feat(${key}): auto-built web app from requirements\n\nJira: ${key}\nPipeline: Zero Human Touch`,
    tree: newTree.sha,
    parents: [baseSha],
  });

  // Update branch ref
  await octokit.git.updateRef({
    owner, repo, ref: `heads/${branchName}`, sha: newCommit.sha,
  });

  // Open Pull Request
  const { data: pr } = await octokit.pulls.create({
    owner, repo,
    title: `[${key}] ${summary}`,
    head: branchName,
    base: 'main',
    body: `## Auto-generated by Zero Human Touch Pipeline\n\n**Jira Story:** ${key}\n**Branch:** ${branchName}\n\nThis PR was created automatically. All code was generated by Groq LLaMA 3.3 70B.`,
  });

  logger.info(`[${key}] Stage 4: PR opened — ${pr.html_url}`);
  return { branchName, prUrl: pr.html_url };
}
